sudo: required
services:
    - docker

before_install:
    - docker build -t lucasrivelles/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lucasrivelles/docker-react npm run test -- --coverage