version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev # Arquivo dentro do contexto atual
        ports:
            - "3000:3000"
        volumes:
            - /webapp/node_modules
            - /c/frontend:/webapp
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /webapp/node_modules
            - /c/frontend:/webapp
        command: ["npm", "run", "test"]